# =====================================================================
# ROMETA - Single-group proportion (prevalence) meta-analysis engine
# Backend R6 class. Inherits from rometaPropBase (auto-generated by
# jmvtools from rometaprop.a.yaml / rometaprop.r.yaml).
#
# Default transformation is logit (PLO), not Freeman-Tukey (PFT): see
# Schwarzer et al. (2019, Res Synth Methods) on misleading back-
# transformation of PFT under unequal sample sizes. PFT remains
# available for comparison/legacy use.
#
# Dual-style forest plot (classic/metafor vs. modern/forestploter) with
# a selectable color theme (Deep Purple accent or Grayscale), mirroring
# rometaDicoto's architecture. Single-arm design: the ilab columns show
# Events/N and Weight.
# =====================================================================

rometaPropClass <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    "rometaPropClass",
    inherit = rometaPropBase,
    private = list(

        .testAdj = function() {
            if (self$options$hksj && self$options$model == 'random') 'knha' else 'z'
        },

        .methodFor = function() {
            if (self$options$model == 'fixed') 'FE' else self$options$tau2Method
        },

        .shortModelLabel = function() {
            opt <- self$options
            if (opt$model == 'fixed') return('FE, Fixed')
            adj <- if (opt$hksj) '-KH' else ''
            paste0(opt$tau2Method, adj, ', Random')
        },

        .bt = function(x, measure, n_ref=NULL) {
            if (measure == 'PR')  return(x)
            if (measure == 'PLO') return(metafor::transf.ilogit(x))
            if (measure == 'PFT') return(metafor::transf.ipft(xi=x, ni=n_ref))
            x
        },

        .run = function() {

            opt <- self$options
            if (is.null(opt$events) || is.null(opt$n)) return()

            data <- self$data
            vars <- c(opt$events, opt$n)
            if (!is.null(opt$labels))   vars <- c(vars, opt$labels)
            if (!is.null(opt$subgroup)) vars <- c(vars, opt$subgroup)
            if (length(opt$moderators)) vars <- c(vars, opt$moderators)

            data <- jmvcore::naOmit(data[, vars, drop=FALSE])
            if (nrow(data) < 2)
                jmvcore::reject('At least two studies are required.')

            xi <- jmvcore::toNumeric(data[[opt$events]])
            ni <- jmvcore::toNumeric(data[[opt$n]])

            if (any(xi > ni, na.rm=TRUE))
                jmvcore::reject('Number of events cannot exceed the total sample size.')

            slabs  <- if (!is.null(opt$labels)) as.character(data[[opt$labels]]) else paste('Study', seq_len(nrow(data)))
            subgrp <- if (!is.null(opt$subgroup)) as.character(data[[opt$subgroup]]) else NULL
            measure <- opt$measure

            es <- try(metafor::escalc(measure=measure, xi=xi, ni=ni, slab=slabs, data=data), silent=TRUE)
            if (inherits(es, 'try-error'))
                jmvcore::reject('Could not compute study-level effect sizes.')

            meth <- private$.methodFor()
            adj  <- private$.testAdj()
            n_global_ref <- 1 / mean(1 / ni)

            model <- try(metafor::rma(yi, vi, data=es, method=meth, test=adj), silent=TRUE)
            if (inherits(model, 'try-error'))
                jmvcore::reject('The overall meta-analytic model failed to converge.')

            self$results$modelTable$setRow(rowNo=1, values=list(
                measure = measure, k = as.integer(model$k),
                estimate = private$.bt(as.numeric(model$b[1]), measure, n_global_ref), se = as.numeric(model$se),
                cil = private$.bt(as.numeric(model$ci.lb[1]), measure, n_global_ref),
                ciu = private$.bt(as.numeric(model$ci.ub[1]), measure, n_global_ref),
                p = as.numeric(model$pval[1]),
                i2 = if(!is.null(model$I2)) as.numeric(model$I2) else NA,
                tau2 = if(!is.null(model$tau2)) as.numeric(model$tau2) else 0,
                qp = if(!is.null(model$QEp)) as.numeric(model$QEp) else NA,
                predLower = NA, predUpper = NA))

            if (opt$model == 'random' && opt$predInt) {
                pr <- try(predict(model), silent=TRUE)
                if (!inherits(pr, 'try-error') && !is.null(pr$pi.lb)) {
                    self$results$modelTable$setRow(rowNo=1, values=list(
                        predLower = private$.bt(pr$pi.lb, measure, n_global_ref),
                        predUpper = private$.bt(pr$pi.ub, measure, n_global_ref)))
                }
            }

            # ---- subgroups -------------------------------------------------
            subgroup_res <- list()
            sub_test <- list(Q=NA, df=NA, p=NA)

            if (!is.null(subgrp)) {
                subTable <- self$results$subgroupTable
                groups <- unique(subgrp)
                usePooled <- (opt$model == 'random' && opt$subgroupModel == 'pooled')

                if (usePooled) {
                    dat_sub <- es; dat_sub$.G <- factor(subgrp)
                    m_means <- try(metafor::rma(yi, vi, mods = ~ .G - 1, data=dat_sub, method=meth, test=adj), silent=TRUE)
                    m_test  <- try(metafor::rma(yi, vi, mods = ~ .G,     data=dat_sub, method=meth, test=adj), silent=TRUE)

                    if (!inherits(m_means, 'try-error')) {
                        cn <- rownames(m_means$beta)
                        for (g in groups) {
                            idx <- which(subgrp == g)
                            n_sub_ref <- 1 / mean(1 / ni[idx])
                            j <- which(cn == paste0('.G', g))
                            if (length(j) == 1) {
                                subgroup_res[[g]] <- list(k=length(idx),
                                    estimate=private$.bt(as.numeric(m_means$beta[j]), measure, n_sub_ref),
                                    cil=private$.bt(as.numeric(m_means$ci.lb[j]), measure, n_sub_ref),
                                    ciu=private$.bt(as.numeric(m_means$ci.ub[j]), measure, n_sub_ref),
                                    p=as.numeric(m_means$pval[j]), i2=NA,
                                    b_raw=as.numeric(m_means$beta[j]), se_raw=as.numeric(m_means$se[j]), n_ref=n_sub_ref)
                            }
                        }
                    }
                    if (!inherits(m_test, 'try-error')) {
                        sub_test$Q <- as.numeric(m_test$QM); sub_test$df <- length(groups) - 1L; sub_test$p <- as.numeric(m_test$QMp)
                    }
                    subTable$setNote('mdl', 'Shared between-study variance (pooled \u03C4\u00B2). Per-subgroup I\u00B2 is not separable under this model.')
                } else {
                    b_est <- c(); se_est <- c()
                    for (g in groups) {
                        idx <- which(subgrp == g)
                        if (length(idx) >= 2) {
                            n_sub_ref <- 1 / mean(1 / ni[idx])
                            sm <- try(metafor::rma(yi, vi, data=es, subset=idx, method=meth, test=adj), silent=TRUE)
                            if (!inherits(sm, 'try-error')) {
                                subgroup_res[[g]] <- list(k=sm$k,
                                    estimate=private$.bt(as.numeric(sm$b[1]), measure, n_sub_ref),
                                    cil=private$.bt(as.numeric(sm$ci.lb[1]), measure, n_sub_ref),
                                    ciu=private$.bt(as.numeric(sm$ci.ub[1]), measure, n_sub_ref),
                                    p=as.numeric(sm$pval[1]), i2=if(!is.null(sm$I2)) as.numeric(sm$I2) else NA,
                                    b_raw=as.numeric(sm$b[1]), se_raw=as.numeric(sm$se[1]), n_ref=n_sub_ref)
                                b_est <- c(b_est, as.numeric(sm$b[1])); se_est <- c(se_est, as.numeric(sm$se[1]))
                            }
                        }
                    }
                    if (length(b_est) >= 2) {
                        btmod <- try(metafor::rma(yi=b_est, sei=se_est, method='FE'), silent=TRUE)
                        if (!inherits(btmod, 'try-error')) {
                            sub_test$Q <- as.numeric(btmod$QE); sub_test$df <- as.integer(btmod$k - 1); sub_test$p <- as.numeric(btmod$QEp)
                        }
                    }
                    note <- if (opt$model == 'fixed')
                        'Fixed-effect model: subgroups pooled with the same fixed method; the variance assumption option does not apply.'
                    else
                        'Separate between-study variance (\u03C4\u00B2) per subgroup.'
                    subTable$setNote('mdl', note)
                }

                for (g in names(subgroup_res)) {
                    sr <- subgroup_res[[g]]
                    subTable$addRow(rowKey=g, values=list(group=g, k=as.integer(sr$k), estimate=sr$estimate,
                        cil=sr$cil, ciu=sr$ciu, p=sr$p, i2=sr$i2))
                }
                if (!is.na(sub_test$Q)) {
                    self$results$subgroupTestTable$setRow(rowNo=1, values=list(
                        qb=sub_test$Q, qbdf=as.integer(sub_test$df), qbp=sub_test$p))
                }
            }

            # ---- meta-regression --------------------------------------------
            mods <- opt$moderators
            if (length(mods) > 0) {
                f <- as.formula(paste('~', paste(sprintf('`%s`', mods), collapse=' + ')))
                dat_reg <- es
                for (mv in mods) dat_reg[[mv]] <- data[[mv]]
                rm <- try(metafor::rma(yi, vi, mods=f, data=dat_reg, method=meth, test=adj), silent=TRUE)
                if (!inherits(rm, 'try-error')) {
                    regT <- self$results$metaRegTable
                    tn <- rownames(rm$beta)
                    for (i in seq_along(tn)) {
                        regT$addRow(rowKey=tn[i], values=list(term=tn[i], estimate=as.numeric(rm$beta[i]),
                            se=as.numeric(rm$se[i]), cil=as.numeric(rm$ci.lb[i]), ciu=as.numeric(rm$ci.ub[i]),
                            p=as.numeric(rm$pval[i])))
                    }
                    self$results$metaRegFitTable$setRow(rowNo=1, values=list(
                        r2=if(!is.null(rm$R2)) as.numeric(rm$R2) else NA,
                        i2res=if(!is.null(rm$I2)) as.numeric(rm$I2) else NA,
                        tau2res=if(!is.null(rm$tau2)) as.numeric(rm$tau2) else NA,
                        qm=as.numeric(rm$QM), qmp=as.numeric(rm$QMp), qe=as.numeric(rm$QE), qep=as.numeric(rm$QEp)))
                    if (length(mods) == 1 && is.numeric(data[[mods[1]]]))
                        self$results$bubblePlot$setState(rm)
                    else
                        self$results$bubblePlot$setState(NULL)
                }
            }

            # ---- publication bias -------------------------------------------
            tf_model <- model
            if (opt$pubBias) {
                biasT <- self$results$biasTable
                if (model$k < 10)
                    biasT$setNote('k', 'Fewer than 10 studies: funnel-asymmetry tests are underpowered and unreliable (Cochrane Handbook).')

                begg <- try(metafor::ranktest(model), silent=TRUE)
                if (!inherits(begg, 'try-error'))
                    biasT$addRow(rowKey='begg', values=list(test="Begg & Mazumdar (Kendall's tau)", value=as.numeric(begg$tau), p=as.numeric(begg$pval)))
                egger <- try(metafor::regtest(model), silent=TRUE)
                if (!inherits(egger, 'try-error'))
                    biasT$addRow(rowKey='egger', values=list(test="Egger's regression (z)", value=as.numeric(egger$zval), p=as.numeric(egger$pval)))

                if (opt$trimFill) {
                    tf <- try(metafor::trimfill(model), silent=TRUE)
                    if (!inherits(tf, 'try-error')) {
                        tf_model <- tf
                        tfT <- self$results$trimFillTable
                        tfT$addRow(rowKey='k0', values=list(test='Imputed studies (k0)', k=as.integer(tf$k0)))
                        tfT$addRow(rowKey='obs', values=list(test='Observed overall effect',
                            estimate=private$.bt(model$b[1], measure, n_global_ref), cil=private$.bt(model$ci.lb[1], measure, n_global_ref),
                            ciu=private$.bt(model$ci.ub[1], measure, n_global_ref), p=as.numeric(model$pval[1])))
                        tfT$addRow(rowKey='adj', values=list(test='Adjusted overall effect (filled)',
                            estimate=private$.bt(tf$b[1], measure, n_global_ref), cil=private$.bt(tf$ci.lb[1], measure, n_global_ref),
                            ciu=private$.bt(tf$ci.ub[1], measure, n_global_ref), p=as.numeric(tf$pval[1])))
                    }
                }
                self$results$funnelPlot$setState(tf_model)
            }

            # ---- send data + visual options to the forest plot --------------
            raw_df <- data.frame(slab=slabs, events=xi, n=ni, stringsAsFactors=FALSE)

            self$results$forestPlot$setState(list(
                model=model, es=es, raw=raw_df, n_global_ref=n_global_ref,
                subgroup=subgrp, subgroup_res=subgroup_res, sub_test=sub_test, measure=measure,
                shortModelLabel=private$.shortModelLabel(),
                style=opt$forestStyle, themeStyle=opt$forestTheme))
        },

        # -------- forest plot (dual style: classic / modern) ---------------

        .forestPlot = function(image, ggtheme, theme, ...) {
            st <- image$state
            if (is.null(st)) return(FALSE)

            dat <- st$es; res <- st$model; raw <- st$raw
            subgrp <- st$subgroup; sg <- st$subgroup_res; sgt <- st$sub_test
            measure <- st$measure; n_global_ref <- st$n_global_ref
            style <- st$style; themeStyle <- st$themeStyle

            n_mean <- mean(raw$n, na.rm=TRUE)
            transf <- function(x) private$.bt(x, measure, n_mean)
            ref <- transf(res$beta[1])   # reference line at the pooled estimate (no natural null for a prevalence)
            xtrans <- 'none'
            est_header <- sprintf('Prop. (95%% CI)\n%s', st$shortModelLabel)

            pesos <- try(metafor::weights.rma.uni(res), silent=TRUE)
            if (inherits(pesos, 'try-error')) pesos <- rep(100/nrow(dat), nrow(dat))

            alpha <- 0.05
            crit <- qnorm(1 - alpha/2)

            evn_str <- paste0(raw$events, '/', raw$n)
            weight_str <- paste0(round(pesos, 1), '%')

            # =================================================================
            # CLASSIC STYLE (metafor)
            # =================================================================
            if (style == 'classic') {

                par(family='sans', mar=c(5, 4, 3, 2), xpd=FALSE,
                    fg='black', col='black', col.axis='black', col.lab='black')

                col_diam <- if (themeStyle == 'gray') '#444444' else '#6A1B9A'
                col_sq   <- col_diam

                min_y <- min(dat$yi - crit * sqrt(dat$vi), na.rm=TRUE)
                max_y <- max(dat$yi + crit * sqrt(dat$vi), na.rm=TRUE)
                span <- max_y - min_y
                if (span == 0) span <- 1

                xlim_c <- c(min_y - span * 2.4, max_y + span * 1.5)
                xpos_evn <- min_y - span * 1.3
                xpos_w   <- min_y - span * 0.6

                ilab_data <- cbind(evn_str, weight_str)

                if (is.null(subgrp)) {
                    ymax <- res$k
                    metafor::forest(res, atransf=transf, refline=ref, showweights=FALSE, header=FALSE,
                                    xlim=xlim_c, ylim=c(-1.5, ymax + 2.5),
                                    ilab=ilab_data, ilab.xpos=c(xpos_evn, xpos_w),
                                    xlab='Proportion', col=col_diam, border=col_diam, col.square=col_sq,
                                    pch=15, efac=1.5, cex=0.95, colout='black')

                    usr <- par('usr')
                    text(usr[1], ymax + 1.5, 'Study', pos=4, font=2, cex=0.95)
                    text(c(xpos_evn, xpos_w), ymax + 1.5, c('Events/N', 'Weight'), font=2, cex=0.95)
                    text(usr[2], ymax + 1.5, est_header, pos=2, font=2, cex=0.95)

                    het <- sprintf('Heterogeneity: I\u00B2 = %.1f%%, \u03C4\u00B2 = %.3f, Q = %.2f, %s',
                                   ifelse(is.null(res$I2), NA, res$I2), ifelse(is.null(res$tau2), 0, res$tau2),
                                   res$QE, ifelse(res$QEp < 0.001, 'p < 0.001', sprintf('p = %.3f', res$QEp)))
                    mtext(het, side=1, line=3.5, adj=0, cex=0.85)
                } else {
                    glev <- sort(unique(subgrp))
                    rows_assigned <- numeric(length(subgrp))
                    poly_assigned <- numeric(length(glev))
                    title_assigned <- numeric(length(glev))
                    y <- 1
                    for (i in length(glev):1) {
                        g <- glev[i]
                        poly_assigned[i] <- y; y <- y + 1
                        idx <- which(subgrp == g)
                        for (j in rev(idx)) { rows_assigned[j] <- y; y <- y + 1 }
                        title_assigned[i] <- y; y <- y + 1.5
                    }
                    ymax <- y

                    metafor::forest(res, rows=rows_assigned, atransf=transf, refline=ref, showweights=FALSE, header=FALSE,
                                    xlim=xlim_c, ylim=c(-1.5, ymax + 2.5),
                                    ilab=ilab_data, ilab.xpos=c(xpos_evn, xpos_w),
                                    xlab='Proportion', col=col_diam, border=col_diam, col.square=col_sq,
                                    pch=15, efac=1.5, cex=0.95, colout='black')

                    usr <- par('usr')
                    text(usr[1], ymax + 1.5, 'Study', pos=4, font=2, cex=0.95)
                    text(c(xpos_evn, xpos_w), ymax + 1.5, c('Events/N', 'Weight'), font=2, cex=0.95)
                    text(usr[2], ymax + 1.5, est_header, pos=2, font=2, cex=0.95)

                    for (i in seq_along(glev)) {
                        g <- glev[i]; sr <- sg[[g]]
                        text(usr[1], title_assigned[i], paste0('Subgroup: ', g), pos=4, font=2, cex=0.95)
                        if (!is.null(sr) && !is.null(sr$b_raw)) {
                            atf_g <- function(x) private$.bt(x, measure, sr$n_ref)
                            metafor::addpoly(x=sr$b_raw, sei=sr$se_raw, atransf=atf_g, rows=poly_assigned[i],
                                             mlab=sprintf('  k = %d', sr$k), col=col_diam, border='black', cex=0.95)
                        }
                    }
                    if (!is.na(sgt$Q)) {
                        sp <- if (sgt$p < 0.001) 'p < 0.001' else sprintf('p = %.3f', sgt$p)
                        mtext(sprintf('Test for subgroup differences: Q = %.2f, df = %d, %s', sgt$Q, sgt$df, sp),
                              side=1, line=3.5, adj=0, cex=0.85, font=3)
                    }
                }
                return(TRUE)
            }

            # =================================================================
            # MODERN STYLE (forestploter)
            # =================================================================
            plot_data <- data.frame(
                Study=raw$slab, 'Events/N' = evn_str, Weight=weight_str,
                Estimate=transf(dat$yi), Lower=transf(dat$yi - crit * sqrt(dat$vi)),
                Upper=transf(dat$yi + crit * sqrt(dat$vi)),
                stringsAsFactors=FALSE, check.names=FALSE)
            plot_data$CI_Text <- sprintf('%.2f [%.2f, %.2f]', plot_data$Estimate, plot_data$Lower, plot_data$Upper)
            plot_data[[' ']] <- paste(rep(' ', 35), collapse=' ')

            final_data <- NULL; is_sum_vec <- c(); sizes_vec <- c()

            if (is.null(subgrp)) {
                final_data <- plot_data
                is_sum_vec <- rep(FALSE, nrow(final_data))
                sizes_vec  <- 0.4 + (pesos / max(pesos)) * 0.4
            } else {
                glev <- sort(unique(subgrp))
                for (g in glev) {
                    header <- data.frame(Study=paste0('Subgroup: ', g), 'Events/N' = '', Weight='',
                                         Estimate=NA, Lower=NA, Upper=NA, CI_Text='', stringsAsFactors=FALSE, check.names=FALSE)
                    header[[' ']] <- ''
                    final_data <- rbind(final_data, header)
                    is_sum_vec <- c(is_sum_vec, TRUE); sizes_vec <- c(sizes_vec, NA)

                    idx <- which(subgrp == g)
                    final_data <- rbind(final_data, plot_data[idx, , drop=FALSE])
                    is_sum_vec <- c(is_sum_vec, rep(FALSE, length(idx)))
                    sizes_vec  <- c(sizes_vec, 0.4 + (pesos[idx] / max(pesos)) * 0.4)

                    sr <- sg[[g]]
                    if (!is.null(sr)) {
                        sum_row <- data.frame(Study=paste0('  Total for ', g), 'Events/N' = '', Weight='',
                                              Estimate=sr$estimate, Lower=sr$cil, Upper=sr$ciu,
                                              CI_Text=sprintf('%.2f [%.2f, %.2f]', sr$estimate, sr$cil, sr$ciu),
                                              stringsAsFactors=FALSE, check.names=FALSE)
                        sum_row[[' ']] <- ''
                        final_data <- rbind(final_data, sum_row)
                        is_sum_vec <- c(is_sum_vec, TRUE); sizes_vec <- c(sizes_vec, 0.8)
                    }
                }
            }

            overall_row <- data.frame(Study='Overall Effect', 'Events/N' = '', Weight='100%',
                                      Estimate=transf(res$beta[1]), Lower=transf(res$ci.lb), Upper=transf(res$ci.ub),
                                      CI_Text=sprintf('%.2f [%.2f, %.2f]', transf(res$beta[1]), transf(res$ci.lb), transf(res$ci.ub)),
                                      stringsAsFactors=FALSE, check.names=FALSE)
            overall_row[[' ']] <- ''
            final_data <- rbind(final_data, overall_row)
            is_sum_vec <- c(is_sum_vec, TRUE); sizes_vec <- c(sizes_vec, 1.0)

            colnames(final_data)[colnames(final_data) == 'CI_Text'] <- est_header

            if (themeStyle == 'gray') {
                diam_fill <- '#333333'; sq_fill <- '#333333'; bg_bands <- c('white', '#F0F0F0')
            } else {
                diam_fill <- '#6A1B9A'; sq_fill <- '#6A1B9A'; bg_bands <- c('white', '#F3E5F5')
            }

            tm <- forestploter::forest_theme(
                base_size = 14, base_family = 'sans',
                refline_gp = grid::gpar(col='#333333', lty='solid'),
                summary_col = 'black', summary_fill = diam_fill,
                ci_pch = 22, ci_col = 'black', ci_fill = sq_fill, ci_alpha = 0.9, ci_lty = 1, ci_lwd = 1.5, ci_Theight = 0.2,
                core = list(bg_params = list(fill = c(rep(bg_bands, length.out = nrow(final_data)-1), 'white')),
                           padding = grid::unit(c(3.0, 4), 'mm')),
                xaxis_gp = grid::gpar(cex = 0.9))

            cols_to_plot <- c('Study', 'Events/N', 'Weight', ' ', est_header)

            p <- forestploter::forest(
                final_data[, cols_to_plot], est=final_data$Estimate, lower=final_data$Lower, upper=final_data$Upper,
                sizes=sizes_vec, ci_column=4, ref_line=ref, x_trans=xtrans, is_summary=is_sum_vec, theme=tm)

            print(p)
            return(TRUE)
        },

        .funnelPlot = function(image, ggtheme, theme, ...) {
            model <- image$state; if (is.null(model)) return(FALSE)
            par(mar=c(5,4,2,2)); metafor::funnel(model, main='Funnel Plot', xlab='Transformed Proportion')
            TRUE
        },

        .bubblePlot = function(image, ggtheme, theme, ...) {
            rm <- image$state; if (is.null(rm)) return(FALSE)
            par(mar=c(5,4,2,2)); metafor::regplot(rm, main='Bubble Plot (Meta-Regression)', xlab='Moderator', col='darkgray', bg='gray')
            TRUE
        }
    )
)
