# =====================================================================
# ROMETA - Dichotomous (2x2) Meta-Analysis engine
# Backend R6 class. Inherits from rometaDicotoBase (auto-generated by
# jmvtools from rometadicoto.a.yaml / rometadicoto.r.yaml).
#
# Pooling aligned with the Cochrane Handbook / RevMan:
#   Fixed effect : Mantel-Haenszel (default), Inverse Variance, or Peto.
#   Random effect: inverse-variance with selectable tau^2 estimator.
# =====================================================================

rometaDicotoClass <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
  "rometaDicotoClass",
  inherit = rometaDicotoBase,
  private = list(
    
    # -------- helpers -----------------------------------------------------
    
    .isRatio = function() {
      self$options$measure %in% c('OR', 'RR', 'PETO')
    },
    
    .bt = function(x) {            
      if (private$.isRatio()) exp(x) else x
    },
    
    .methodLabel = function() {
      opt <- self$options
      if (opt$model == 'fixed') {
        if (opt$measure == 'PETO') return('Fixed effect (Peto)')
        if (opt$feMethod == 'MH') return('Fixed effect (Mantel-Haenszel)')
        return('Fixed effect (Inverse Variance)')
      }
      adj <- if (opt$hksj) ', Knapp-Hartung' else ''
      paste0('Random effects (', opt$tau2Method, adj, ')')
    },
    
    .shortModelLabel = function() {
      opt <- self$options
      if (opt$model == 'fixed') {
        if (opt$measure == 'PETO') return('Peto, Fixed')
        if (opt$feMethod == 'MH') return('M-H, Fixed')
        return('IV, Fixed')
      }
      return(paste0(opt$tau2Method, ', Random'))
    },
    
    .testAdj = function() {
      if (self$options$hksj && self$options$model == 'random') 'knha' else 'z'
    },
    
    .fitOne = function(es, ai, bi, ci, di, slab, idx=NULL) {
      opt <- self$options
      if (!is.null(idx)) {
        es  <- es[idx, , drop=FALSE]
        ai  <- ai[idx]; bi <- bi[idx]; ci <- ci[idx]; di <- di[idx]
        slab <- slab[idx]
      }
      addv <- if (opt$cc == 'none') 0 else 1/2
      tow  <- if (opt$cc == 'all') 'all' else if (opt$cc == 'only0') 'only0' else 'none'
      
      if (opt$model == 'fixed') {
        if (opt$measure == 'PETO') {
          m <- try(metafor::rma.peto(ai=ai, bi=bi, ci=ci, di=di, add=addv, to=tow, slab=slab), silent=TRUE)
        } else if (opt$feMethod == 'MH') {
          m <- try(metafor::rma.mh(ai=ai, bi=bi, ci=ci, di=di, measure=opt$measure, add=addv, to=tow, slab=slab), silent=TRUE)
        } else {
          m <- try(metafor::rma(yi, vi, data=es, method='FE', slab=slab), silent=TRUE)
        }
      } else {
        m <- try(metafor::rma(yi, vi, data=es, method=opt$tau2Method, test=private$.testAdj(), slab=slab), silent=TRUE)
      }
      m
    },
    
    .extract = function(m) {
      isR <- private$.isRatio()
      bt  <- function(x) if (isR) exp(x) else x
      list(k = m$k, b_raw = as.numeric(m$beta[1]), se = as.numeric(m$se[1]), est = bt(as.numeric(m$beta[1])),
           ci.lb = bt(as.numeric(m$ci.lb[1])), ci.ub = bt(as.numeric(m$ci.ub[1])), zval = if (!is.null(m$zval)) as.numeric(m$zval[1]) else NA,
           pval = as.numeric(m$pval[1]), tau2 = if (!is.null(m$tau2)) as.numeric(m$tau2) else 0, I2 = if (!is.null(m$I2)) as.numeric(m$I2) else NA,
           H2 = if (!is.null(m$H2)) as.numeric(m$H2) else NA, QE = if (!is.null(m$QE)) as.numeric(m$QE) else NA,
           QEdf = if (!is.null(m$k)) as.integer(m$k - m$p) else NA, QEp = if (!is.null(m$QEp)) as.numeric(m$QEp) else NA)
    },
    
    # -------- main run ----------------------------------------------------
    
    .run = function() {
      
      opt <- self$options
      if (is.null(opt$te) || is.null(opt$tn) || is.null(opt$ce) || is.null(opt$cn))
        return()
      
      data <- self$data
      vars <- c(opt$te, opt$tn, opt$ce, opt$cn)
      if (!is.null(opt$labels))    vars <- c(vars, opt$labels)
      if (!is.null(opt$subgroup))  vars <- c(vars, opt$subgroup)
      if (length(opt$moderators))  vars <- c(vars, opt$moderators)
      
      data <- jmvcore::naOmit(data[, vars, drop=FALSE])
      if (nrow(data) < 2)
        jmvcore::reject('At least two studies are required.')
      
      ai  <- jmvcore::toNumeric(data[[opt$te]])    
      n1i <- jmvcore::toNumeric(data[[opt$tn]])    
      ci  <- jmvcore::toNumeric(data[[opt$ce]])    
      n2i <- jmvcore::toNumeric(data[[opt$cn]])    
      bi  <- n1i - ai                              
      di  <- n2i - ci                              
      
      if (any(c(ai, bi, ci, di) < 0, na.rm=TRUE))
        jmvcore::reject('Events cannot exceed the total sample size. Check the data columns.')
      
      slabs  <- if (!is.null(opt$labels)) as.character(data[[opt$labels]]) else paste('Study', seq_len(nrow(data)))
      subgrp <- if (!is.null(opt$subgroup)) as.character(data[[opt$subgroup]]) else NULL
      
      measure <- opt$measure
      isRatio <- private$.isRatio()
      addv <- if (opt$cc == 'none') 0 else 1/2
      tow  <- if (opt$cc == 'all') 'all' else if (opt$cc == 'only0') 'only0' else 'none'
      
      es <- try(metafor::escalc(measure = measure, ai=ai, bi=bi, ci=ci, di=di, add=addv, to=tow, slab=slabs), silent=TRUE)
      if (inherits(es, 'try-error')) jmvcore::reject('Could not compute study-level effect sizes. Check for empty or invalid cells.')
      
      model <- private$.fitOne(es, ai, bi, ci, di, slabs)
      if (inherits(model, 'try-error')) jmvcore::reject('The overall meta-analytic model failed to converge.')
      
      ex <- private$.extract(model)
      
      self$results$modelTable$setRow(rowNo=1, values=list(
        measure  = switch(measure, RR='Risk Ratio', OR='Odds Ratio', RD='Risk Difference', PETO='Peto Odds Ratio'),
        method   = private$.methodLabel(), k = as.integer(ex$k), estimate = ex$est, cil = ex$ci.lb, ciu = ex$ci.ub,
        se = ex$se, zval = ex$zval, p = ex$pval, predLower = NA, predUpper = NA))
      
      if (opt$model == 'random' && opt$predInt) {
        pr <- try(predict(model), silent=TRUE)
        if (!inherits(pr, 'try-error') && !is.null(pr$pi.lb)) {
          self$results$modelTable$setRow(rowNo=1, values=list(predLower = private$.bt(pr$pi.lb), predUpper = private$.bt(pr$pi.ub)))
        }
      }
      
      self$results$hetTable$setRow(rowNo=1, values=list(tau2 = ex$tau2, i2 = ex$I2, h2 = ex$H2, q = ex$QE, qdf = ex$QEdf, qp = ex$QEp))
      
      # ---- subgroups ----
      subgroup_res <- list()
      sub_test <- list(Q=NA, df=NA, p=NA)
      
      if (!is.null(subgrp)) {
        subTable <- self$results$subgroupTable
        groups <- unique(subgrp)
        usePooled <- (opt$model == 'random' && opt$subgroupModel == 'pooled')
        
        if (usePooled) {
          dat_sub <- es; dat_sub$.G <- factor(subgrp)
          m_means <- try(metafor::rma(yi, vi, mods = ~ .G - 1, data=dat_sub, method=opt$tau2Method, test=private$.testAdj()), silent=TRUE)
          m_test  <- try(metafor::rma(yi, vi, mods = ~ .G, data=dat_sub, method=opt$tau2Method, test=private$.testAdj()), silent=TRUE)
          
          if (!inherits(m_means, 'try-error')) {
            cn <- rownames(m_means$beta)
            for (g in groups) {
              idx <- which(subgrp == g)
              tgt <- paste0('.G', g)
              j <- which(cn == tgt)
              if (length(j) == 1) {
                subgroup_res[[g]] <- list(k = length(idx), b_raw = as.numeric(m_means$beta[j]), se = as.numeric(m_means$se[j]),
                                          est = private$.bt(m_means$beta[j]), ci.lb = private$.bt(m_means$ci.lb[j]),
                                          ci.ub = private$.bt(m_means$ci.ub[j]), p = as.numeric(m_means$pval[j]), I2 = NA)
              }
            }
          }
          if (!inherits(m_test, 'try-error')) {
            sub_test$Q <- as.numeric(m_test$QM); sub_test$df <- length(groups) - 1L; sub_test$p <- as.numeric(m_test$QMp)
          }
          subTable$setNote('mdl', 'Shared between-study variance (pooled \u03C4\u00B2). Per-subgroup I\u00B2 is not separable under this model.')
        } else {
          b_est <- c(); se_est <- c()
          for (g in groups) {
            idx <- which(subgrp == g)
            if (length(idx) >= 2) {
              sm <- private$.fitOne(es, ai, bi, ci, di, slabs, idx=idx)
              if (!inherits(sm, 'try-error')) {
                sx <- private$.extract(sm)
                subgroup_res[[g]] <- list(k=sx$k, b_raw=sx$b_raw, se=sx$se, est=sx$est, ci.lb=sx$ci.lb, ci.ub=sx$ci.ub, p=sx$pval, I2=sx$I2)
                b_est <- c(b_est, sx$b_raw); se_est <- c(se_est, sx$se)
              }
            }
          }
          if (length(b_est) >= 2) {
            bt_mod <- try(metafor::rma(yi=b_est, sei=se_est, method='FE'), silent=TRUE)
            if (!inherits(bt_mod, 'try-error')) { sub_test$Q <- as.numeric(bt_mod$QE); sub_test$df <- as.integer(bt_mod$k - 1); sub_test$p <- as.numeric(bt_mod$QEp) }
          }
          note <- if (opt$model == 'fixed') 'Fixed-effect model: subgroups pooled with the same fixed method.' else 'Separate between-study variance (\u03C4\u00B2) per subgroup.'
          subTable$setNote('mdl', note)
        }
        
        for (g in names(subgroup_res)) {
          sr <- subgroup_res[[g]]
          subTable$addRow(rowKey=g, values=list(group=g, k=as.integer(sr$k), estimate=sr$est, cil=sr$ci.lb, ciu=sr$ci.ub, p=sr$p, i2=sr$I2))
        }
        if (!is.na(sub_test$Q)) { self$results$subgroupTestTable$setRow(rowNo=1, values=list(qb=sub_test$Q, qbdf=as.integer(sub_test$df), qbp=sub_test$p)) }
      }
      
      # ---- meta-regression ----
      mods <- opt$moderators
      if (length(mods) > 0) {
        dat_reg <- es
        for (mv in mods) dat_reg[[mv]] <- data[[mv]]
        f <- as.formula(paste('~', paste(sprintf('`%s`', mods), collapse=' + ')))
        rm <- try(metafor::rma(yi, vi, mods=f, data=dat_reg, method=if (opt$model=='fixed') 'FE' else opt$tau2Method, test=private$.testAdj()), silent=TRUE)
        if (!inherits(rm, 'try-error')) {
          regT <- self$results$metaRegTable
          tn <- rownames(rm$beta)
          for (i in seq_along(tn)) {
            b <- as.numeric(rm$beta[i])
            regT$addRow(rowKey=tn[i], values=list(term=tn[i], estimate=b, expest=if (isRatio) exp(b) else NA,
                                                  se=as.numeric(rm$se[i]), cil=as.numeric(rm$ci.lb[i]), ciu=as.numeric(rm$ci.ub[i]), p=as.numeric(rm$pval[i])))
          }
          self$results$metaRegFitTable$setRow(rowNo=1, values=list(qm=as.numeric(rm$QM), qmp=as.numeric(rm$QMp), qe=as.numeric(rm$QE), qep=as.numeric(rm$QEp),
                                                                   i2res=if(!is.null(rm$I2)) as.numeric(rm$I2) else NA, tau2res=if(!is.null(rm$tau2)) as.numeric(rm$tau2) else NA, r2=if(!is.null(rm$R2)) as.numeric(rm$R2) else NA))
          if (isRatio) self$results$metaRegTable$setNote('exp', 'exp(Estimate) gives the multiplicative change in the ratio.')
          if (length(mods) == 1 && is.numeric(data[[mods[1]]])) self$results$bubblePlot$setState(list(model=rm, isRatio=isRatio)) else self$results$bubblePlot$setState(NULL)
        }
      }
      
      # ---- publication bias ----
      tf_model <- model
      if (opt$pubBias) {
        biasT <- self$results$biasTable
        if (ex$k < 10) biasT$setNote('k', 'Fewer than 10 studies: funnel-asymmetry tests are underpowered.')
        biasT$setNote('rec', 'For odds ratios, Harbord’s modified test is preferred over Egger’s. Interpret with caution.')
        
        mref <- if (inherits(model, 'rma.uni')) model else try(metafor::rma(yi, vi, data=es, method=if (opt$model=='fixed') 'FE' else opt$tau2Method, test=private$.testAdj()), silent=TRUE)
        
        if (!inherits(mref, 'try-error')) {
          egg <- try(metafor::regtest(mref), silent=TRUE)
          if (!inherits(egg, 'try-error')) biasT$addRow(rowKey='egger', values=list(test="Egger's regression (z)", value=as.numeric(egg$zval), p=as.numeric(egg$pval)))
          
          if (measure == 'OR') {
            Ni <- n1i + n2i
            Z_h <- ai - (n1i * (ai + ci)) / Ni
            V_h <- (n1i * n2i * (ai + ci) * (bi + di)) / (Ni^2 * (Ni - 1))
            valid <- !is.na(V_h) & (V_h > 0)
            
            if (sum(valid) >= 3) {
              y_h <- Z_h[valid] / sqrt(V_h[valid])
              x_h <- sqrt(V_h[valid])
              fit_h <- try(lm(y_h ~ x_h), silent=TRUE)
              if (!inherits(fit_h, 'try-error')) {
                sm_h <- summary(fit_h)
                if (nrow(sm_h$coefficients) >= 1) {
                  biasT$addRow(rowKey='harbord', values=list(test="Harbord's modified test (t)", value=as.numeric(sm_h$coefficients[1, "t value"]), p=as.numeric(sm_h$coefficients[1, "Pr(>|t|)"])))
                }
              }
            }
          }
          
          beg <- try(metafor::ranktest(mref), silent=TRUE)
          if (!inherits(beg, 'try-error')) biasT$addRow(rowKey='begg', values=list(test="Begg & Mazumdar (Kendall's tau)", value=as.numeric(beg$tau), p=as.numeric(beg$pval)))
          
          if (opt$trimFill) {
            tf <- try(metafor::trimfill(mref), silent=TRUE)
            if (!inherits(tf, 'try-error')) {
              tf_model <- tf
              tfT <- self$results$trimFillTable
              tfT$addRow(rowKey='k0', values=list(test='Imputed studies (k0)', k=as.integer(tf$k0)))
              tfT$addRow(rowKey='obs', values=list(test='Observed overall effect', estimate=private$.bt(mref$beta[1]), cil=private$.bt(mref$ci.lb[1]), ciu=private$.bt(mref$ci.ub[1]), p=as.numeric(mref$pval[1])))
              tfT$addRow(rowKey='adj', values=list(test='Adjusted overall effect (filled)', estimate=private$.bt(tf$beta[1]), cil=private$.bt(tf$ci.lb[1]), ciu=private$.bt(tf$ci.ub[1]), p=as.numeric(tf$pval[1])))
            }
          }
        }
        self$results$funnelPlot$setState(list(model=tf_model, measure=measure))
      }
      
      # ---- PREPARAR DATOS Y ENVIAR OPCIONES VISUALES AL PLOT ----
      raw_df <- data.frame(slab = slabs, ai = ai, bi = bi, ci = ci, di = di, stringsAsFactors = FALSE)
      
      self$results$forestPlot$setState(list(
        model=model, es=es, raw=raw_df, subgroup=subgrp,
        subgroup_res=subgroup_res, sub_test=sub_test,
        measure=measure, isRatio=isRatio,
        shortModelLabel=private$.shortModelLabel(),
        
        style = opt$forestStyle,
        themeStyle = opt$forestTheme
      ))
    },
    
    # -------- forest plot (Doble Estilo: Clásico y Moderno) ----------------
    
    .forestPlot = function(image, ggtheme, theme, ...) {
      st <- image$state
      if (is.null(st)) return(FALSE)
      
      dat     <- st$es
      res     <- st$model
      raw     <- st$raw
      subgrp  <- st$subgroup
      sg      <- st$subgroup_res
      sgt     <- st$sub_test
      measure <- st$measure
      isRatio <- st$isRatio
      
      style      <- st$style
      themeStyle <- st$themeStyle
      
      transf <- if (isRatio) exp else function(x) x
      ref    <- if (isRatio) 1 else 0
      xtrans <- if (isRatio) "log" else "none"
      meas_label <- switch(measure, RR="RR", OR="OR", PETO="Peto OR", RD="RD")
      
      # Construcción del Header Estilo RevMan
      est_header <- sprintf("%s (95%% CI)\n%s", meas_label, st$shortModelLabel)
      
      pesos <- try(metafor::weights.rma.uni(res), silent=TRUE)
      if (inherits(pesos, "try-error")) pesos <- rep(100/nrow(dat), nrow(dat))
      
      alpha <- 0.05
      crit <- qnorm(1 - alpha/2)
      
      # Generamos los textos para las columnas extra
      treat_str <- paste0(raw$ai, "/", raw$ai + raw$bi)
      ctrl_str  <- paste0(raw$ci, "/", raw$ci + raw$di)
      weight_str <- paste0(round(pesos, 1), "%")
      
      
      # =================================================================
      # ESTILO CLÁSICO (metafor)
      # =================================================================
      if (style == "classic") {
        
        # Forzamos que todos los elementos gráficos base sean negros
        par(family='sans', mar=c(5, 4, 3, 2), xpd=FALSE, 
            fg="black", col="black", col.axis="black", col.lab="black")
        
        # Tema profundo o gris solo para cuadrados y diamantes
        col_diam <- if (themeStyle == "blue") "#0D47A1" else "#444444"
        col_sq   <- if (themeStyle == "blue") "#0D47A1" else "#444444"
        
        # Calculamos una posición dinámica para evitar solapamientos
        min_y <- min(dat$yi - crit * sqrt(dat$vi), na.rm=TRUE)
        max_y <- max(dat$yi + crit * sqrt(dat$vi), na.rm=TRUE)
        span <- max_y - min_y
        if(span == 0) span <- 1
        
        # Aumentamos agresivamente el límite izquierdo para meter las columnas
        xlim_c <- c(min_y - span * 3.0, max_y + span * 1.5)
        
        # Coordenadas X para las columnas (Treatment, Control, Weight)
        xpos_treat  <- min_y - span * 1.8
        xpos_ctrl   <- min_y - span * 1.2
        xpos_weight <- min_y - span * 0.6
        
        ilab_data <- cbind(treat_str, ctrl_str, weight_str)
        
        if (is.null(subgrp)) {
          ymax <- res$k
          metafor::forest(res, atransf=transf, refline=ref, showweights=FALSE, header=FALSE,
                          xlim=xlim_c, ylim=c(-1.5, ymax + 2.5), 
                          ilab=ilab_data, ilab.xpos=c(xpos_treat, xpos_ctrl, xpos_weight),
                          xlab=meas_label, 
                          col=col_diam, border=col_diam, col.square=col_sq,
                          pch=15, efac=1.5, cex=0.95, colout="black")
          
          # Añadir Encabezados Manualmente (Alineación perfecta)
          usr <- par("usr")
          text(usr[1], ymax + 1.5, "Study", pos=4, font=2, cex=0.95)
          text(c(xpos_treat, xpos_ctrl, xpos_weight), ymax + 1.5, c("Treatment", "Control", "Weight"), font=2, cex=0.95)
          text(usr[2], ymax + 1.5, est_header, pos=2, font=2, cex=0.95)
          
          het <- sprintf('Heterogeneity: I\u00B2 = %.1f%%, \u03C4\u00B2 = %.3f, Q = %.2f, %s',
                         ifelse(is.null(res$I2), NA, res$I2), ifelse(is.null(res$tau2), 0, res$tau2),
                         res$QE, ifelse(res$QEp < 0.001, 'p < 0.001', sprintf('p = %.3f', res$QEp)))
          mtext(het, side=1, line=3.5, adj=0, cex=0.85)
        } else {
          glev <- sort(unique(subgrp))
          rows_assigned <- numeric(length(subgrp))
          poly_assigned <- numeric(length(glev))
          title_assigned <- numeric(length(glev))
          y <- 1
          for (i in length(glev):1) {
            g <- glev[i]
            poly_assigned[i] <- y; y <- y + 1
            idx <- which(subgrp == g)
            for (j in rev(idx)) { rows_assigned[j] <- y; y <- y + 1 }
            title_assigned[i] <- y; y <- y + 1.5
          }
          ymax <- y
          
          metafor::forest(res, rows=rows_assigned, atransf=transf, refline=ref, showweights=FALSE, header=FALSE,
                          xlim=xlim_c, ylim=c(-1.5, ymax + 2.5), 
                          ilab=ilab_data, ilab.xpos=c(xpos_treat, xpos_ctrl, xpos_weight),
                          xlab=meas_label, col=col_diam, border=col_diam, col.square=col_sq, 
                          pch=15, efac=1.5, cex=0.95, colout="black")
          
          # Añadir Encabezados Manualmente
          usr <- par("usr")
          text(usr[1], ymax + 1.5, "Study", pos=4, font=2, cex=0.95)
          text(c(xpos_treat, xpos_ctrl, xpos_weight), ymax + 1.5, c("Treatment", "Control", "Weight"), font=2, cex=0.95)
          text(usr[2], ymax + 1.5, est_header, pos=2, font=2, cex=0.95)
          
          for (i in seq_along(glev)) {
            g  <- glev[i]; sr <- sg[[g]]
            text(usr[1], title_assigned[i], paste0('Subgroup: ', g), pos=4, font=2, cex=0.95)
            if (!is.null(sr)) {
              metafor::addpoly(x=sr$b_raw, sei=sr$se, atransf=transf, rows=poly_assigned[i], mlab=sprintf('  k = %d', sr$k),
                               col=if (themeStyle=="blue") "#8AB4F8" else "#888888", border="black", cex=0.95) 
            }
          }
          if (!is.na(sgt$Q)) {
            sp <- if (sgt$p < 0.001) 'p < 0.001' else sprintf('p = %.3f', sgt$p)
            mtext(sprintf('Test for subgroup differences: Q = %.2f, df = %d, %s', sgt$Q, sgt$df, sp), side=1, line=3.5, adj=0, cex=0.85, font=3)
          }
        }
        return(TRUE)
      }
      
      # =================================================================
      # ESTILO MODERNO (forestploter)
      # =================================================================
      plot_data <- data.frame(
        Study     = raw$slab,
        Treatment = treat_str,
        Control   = ctrl_str,
        Weight    = weight_str,
        Estimate  = transf(dat$yi),
        Lower     = transf(dat$yi - crit * sqrt(dat$vi)),
        Upper     = transf(dat$yi + crit * sqrt(dat$vi)),
        stringsAsFactors = FALSE, check.names = FALSE
      )
      plot_data$CI_Text <- sprintf("%.2f [%.2f, %.2f]", plot_data$Estimate, plot_data$Lower, plot_data$Upper)
      
      # Ampliamos los espacios vacíos para asegurar que la barra y el eje X tengan lugar
      plot_data[[" "]] <- paste(rep(" ", 35), collapse = " ")
      
      final_data <- NULL
      is_sum_vec <- c()
      sizes_vec  <- c()
      
      if (is.null(subgrp)) {
        final_data <- plot_data
        is_sum_vec <- rep(FALSE, nrow(final_data))
        sizes_vec  <- 0.4 + (pesos / max(pesos)) * 0.4 
      } else {
        glev <- sort(unique(subgrp))
        for (g in glev) {
          header <- data.frame(Study = paste0("Subgroup: ", g), Treatment = "", Control = "", Weight = "", Estimate = NA, Lower = NA, Upper = NA, CI_Text = "", stringsAsFactors = FALSE, check.names = FALSE)
          header[[" "]] <- ""
          final_data <- rbind(final_data, header)
          is_sum_vec <- c(is_sum_vec, TRUE)
          sizes_vec  <- c(sizes_vec, NA)
          
          idx <- which(subgrp == g)
          final_data <- rbind(final_data, plot_data[idx, , drop = FALSE])
          is_sum_vec <- c(is_sum_vec, rep(FALSE, length(idx)))
          sizes_vec  <- c(sizes_vec, 0.4 + (pesos[idx] / max(pesos)) * 0.4)
          
          sr <- sg[[g]]
          if (!is.null(sr)) {
            sum_row <- data.frame(Study = paste0("  Total for ", g), Treatment = "", Control = "", Weight = "", Estimate = sr$est, Lower = sr$ci.lb, Upper = sr$ci.ub, CI_Text = sprintf("%.2f [%.2f, %.2f]", sr$est, sr$ci.lb, sr$ci.ub), stringsAsFactors = FALSE, check.names = FALSE)
            sum_row[[" "]] <- ""
            final_data <- rbind(final_data, sum_row)
            is_sum_vec <- c(is_sum_vec, TRUE)
            sizes_vec  <- c(sizes_vec, 0.8)
          }
        }
      }
      
      overall_row <- data.frame(Study = "Overall Effect", Treatment = "", Control = "", Weight = "100%", Estimate = transf(res$beta[1]), Lower = transf(res$ci.lb), Upper = transf(res$ci.ub), CI_Text = sprintf("%.2f [%.2f, %.2f]", transf(res$beta[1]), transf(res$ci.lb), transf(res$ci.ub)), stringsAsFactors = FALSE, check.names = FALSE)
      overall_row[[" "]] <- ""
      final_data <- rbind(final_data, overall_row)
      is_sum_vec <- c(is_sum_vec, TRUE)
      sizes_vec  <- c(sizes_vec, 1.0)
      
      # Asignamos el header dinámico
      colnames(final_data)[colnames(final_data) == "CI_Text"] <- est_header
      
      # Configuración de Colores según menú
      if (themeStyle == "blue") {
        diam_fill <- "#0D47A1"  # Azul profundo diamante
        sq_fill   <- "#0D47A1"  # Azul profundo interior de los cuadrados
        bg_bands  <- c("white", "#F0F4F8") 
      } else {
        diam_fill <- "#333333"  
        sq_fill   <- "#333333"  
        bg_bands  <- c("white", "#F0F0F0") 
      }
      
      tm <- forestploter::forest_theme(
        base_size = 14,
        base_family = "sans",
        refline_gp = grid::gpar(col = "#333333", lty = "solid"),
        summary_col = "black",        # Borde del diamante en negro
        summary_fill = diam_fill,     # Relleno del diamante
        ci_pch = 22,                  # 22 es un cuadrado que permite relleno y borde independiente
        ci_col = "black",             # Intervalos (bigotes) y bordes de los cuadrados en negro
        ci_fill = sq_fill,            # Relleno azul profundo de los cuadrados
        ci_alpha = 0.9,
        ci_lty = 1,
        ci_lwd = 1.5,
        ci_Theight = 0.2,
        core = list(
          bg_params = list(fill = c(rep(bg_bands, length.out = nrow(final_data)-1), "white")),
          padding = grid::unit(c(3.0, 4), "mm") # Reducimos ligeramente el espaciado vertical
        ),
        xaxis_gp = grid::gpar(cex = 0.9)
      )
      
      cols_to_plot <- c("Study", "Treatment", "Control", "Weight", " ", est_header)
      
      p <- forestploter::forest(
        final_data[, cols_to_plot],
        est = final_data$Estimate,
        lower = final_data$Lower,
        upper = final_data$Upper,
        sizes = sizes_vec,
        ci_column = 5,
        ref_line = ref,
        x_trans = xtrans,
        is_summary = is_sum_vec,
        theme = tm
      )
      
      print(p)
      return(TRUE)
    },
    
    # -------- funnel & bubble ---------------------------------------------
    .funnelPlot = function(image, ggtheme, theme, ...) {
      st <- image$state
      if (is.null(st)) return(FALSE)
      par(family='serif')
      metafor::funnel(st$model, main='Funnel Plot',
                      xlab=switch(st$measure, RR='log Risk Ratio', OR='log Odds Ratio', PETO='log Peto OR', RD='Risk Difference'))
      TRUE
    },
    
    .bubblePlot = function(image, ggtheme, theme, ...) {
      st <- image$state
      if (is.null(st)) return(FALSE)
      par(family='serif')
      metafor::regplot(st$model, transf=if (st$isRatio) exp else NULL, main='Bubble Plot (Meta-Regression)', xlab='Moderator')
      TRUE
    }
  )
)